In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd

We select the same training lakes as the SLIDE algorithm does https://ieeexplore.ieee.org/document/9462830

In [3]:
slide_training_data = pd.read_csv("/mnt/Data_2tb/sentinel1_ice/training data.csv")

In [7]:
lake_ids = slide_training_data.Hylak_id.unique()
len(lake_ids)

1360

# Export polygons of these lakes

In [9]:
hydrolakes = gpd.read_file("/mnt/Data_2tb/HydroSHEDS/HydroLAKES_polys_v10_shp/HydroLAKES_polys_v10_shp/HydroLAKES_polys_v10.shp")
hydrolakes

,Hylak_id,Lake_name,Country,Continent,Poly_src,Lake_type,Grand_id,Lake_area,Shore_len,Shore_dev,...,Vol_src,Depth_avg,Dis_avg,Res_time,Elevation,Slope_100,Wshd_area,Pour_long,Pour_lat,geometry
0,1,Caspian Sea,Russia,Europe,SWBD,1,0,377001.91,15829.37,7.27,...,1,200.5,8110.642,107883.0,-29,-1.00,1404108.0,47.717708,45.591934,"POLYGON ((49.96181 37.43847, 49.96457 37.44022..."
1,2,Great Bear,Canada,North America,CanVec,1,0,30450.64,5331.72,8.62,...,1,72.2,535.187,47577.7,145,-1.00,147665.4,-123.505546,65.138384,"POLYGON ((-119.78782 67.03574, -119.78637 67.0..."
2,3,Great Slave,Canada,North America,CanVec,1,0,26734.29,9814.16,16.93,...,1,59.1,4350.692,4203.2,148,-1.00,995312.3,-117.617115,61.311727,"POLYGON ((-109.93976 62.95851, -109.93831 62.9..."
3,4,Winnipeg,Canada,North America,CanVec,3,709,23923.04,4018.32,7.33,...,1,11.9,2244.727,1464.3,215,-1.00,919611.5,-97.863542,53.696359,"POLYGON ((-98.80636 53.88021, -98.80578 53.880..."
4,5,Superior,United States of America,North America,SWBD,1,0,81843.92,5248.36,5.18,...,1,146.7,2869.953,48410.3,179,-1.00,209219.5,-84.460547,46.468593,"POLYGON ((-90.72250 46.65740, -90.72458 46.657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427683,1427684,NaN,New Zealand,Oceania,SWBD,1,0,0.29,2.30,1.20,...,3,5.1,0.125,139.6,1,4.83,4.4,169.147152,-52.592307,"POLYGON ((169.14763 -52.59291, 169.14750 -52.5..."
1427684,1427685,NaN,Australia,Oceania,SWBD,1,0,0.10,1.66,1.52,...,3,2.1,-9999.000,-9999.0,1,1.04,-9999.0,73.305108,-52.973622,"POLYGON ((73.30605 -52.97318, 73.30540 -52.974..."
1427685,1427686,NaN,Australia,Oceania,SWBD,1,0,0.24,1.92,1.10,...,3,3.7,0.013,792.4,205,2.63,0.2,158.892278,-54.529970,"POLYGON ((158.89124 -54.53117, 158.88696 -54.5..."
1427686,1427687,NaN,Australia,Oceania,SWBD,1,0,0.34,2.95,1.44,...,3,6.5,0.020,1263.9,163,7.58,0.4,158.889583,-54.594300,"POLYGON ((158.88858 -54.59767, 158.88833 -54.5..."
1427687,1427688,NaN,Australia,Oceania,SWBD,1,0,0.44,3.06,1.30,...,3,6.4,0.073,452.1,187,6.77,1.4,158.835417,-54.686534,"POLYGON ((158.83901 -54.68744, 158.83867 -54.6..."

In [10]:
training_lakes = hydrolakes.loc[hydrolakes.Hylak_id.isin(lake_ids)]

In [12]:
training_lakes.to_file("/mnt/Data_2tb/sentinel1_ice/lake_polys/traing_lakes_s1_s2.shp")

In [15]:
training_lakes.set_index("Hylak_id").to_csv("data/training_lakes.csv")